name: CI

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '30 5,17 * * *'
  watch:
    types:
      - started



jobs:
  build:
    name: Build binary CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip3 install requests && pip3 install colorama && python3 login.py


